// ======================================
// PRODUCTION
// ======================================

### Get all manufacturers
GET https://cse-341-project2-6513.onrender.com/manufacturers

### Get manufacturer by ID
GET https://cse-341-project2-6513.onrender.com/manufacturers/6918fd3796fa369ccd36c4e4

### Create a new manufacturer
POST https://cse-341-project2-6513.onrender.com/manufacturers
Content-Type: application/json

{
  "name": "Honda",
  "country": "Japan"
}

### Update a manufacturer
PUT https://cse-341-project2-6513.onrender.com/manufacturers/6918fd3796fa369ccd36c4e4
Content-Type: application/json

{
  "name": "Toyota",
  "country": "Japan"
}

### Delete a manufacturer
DELETE https://cse-341-project2-6513.onrender.com/manufacturers/6918fd3796fa369ccd36c4e4

### Get all cars
GET https://cse-341-project2-6513.onrender.com/cars

### Get car by ID
GET https://cse-341-project2-6513.onrender.com/cars/6918fffefc6602bc1c614979

### Create a new car
POST https://cse-341-project2-6513.onrender.com/cars
Content-Type: application/json

{
  "model": "Civic",
  "year": 2022,
  "manufacturer": "6918fd3796fa369ccd36c4e4"
}

### Update a car
PUT https://cse-341-project2-6513.onrender.com/cars/6918fffefc6602bc1c614979
Content-Type: application/json

{
  "model": "Corolla",
  "year": 2020,
  "manufacturer": "6918fd3796fa369ccd36c4e4"
}

### Delete a car
DELETE https://cse-341-project2-6513.onrender.com/cars/6918fffefc6602bc1c614979


// ======================================
// LOCALHOST
// ======================================

### Get all manufacturers
GET http://localhost:8080/manufacturers

### Get manufacturer by ID
GET http://localhost:8080/manufacturers/6918fd3796fa369ccd36c4e4

### Create a new manufacturer
POST http://localhost:8080/manufacturers
Content-Type: application/json

{
  "name": "Honda",
  "country": "Japan"
}

### Update a manufacturer
PUT http://localhost:8080/manufacturers/6918fd3796fa369ccd36c4e4
Content-Type: application/json

{
  "name": "Toyota",
  "country": "Japan"
}

### Delete a manufacturer
DELETE http://localhost:8080/manufacturers/6918fd3796fa369ccd36c4e4

### Get all cars
GET http://localhost:8080/cars

### Get car by ID
GET http://localhost:8080/cars/6918fffefc6602bc1c614979

### Create a new car
POST http://localhost:8080/cars
Content-Type: application/json

{
  "model": "Civic",
  "year": 2022,
  "manufacturer": "6918fd3796fa369ccd36c4e4"
}

### Update a car
PUT http://localhost:8080/cars/6918fffefc6602bc1c614979
Content-Type: application/json

{
  "model": "Corolla",
  "year": 2020,
  "manufacturer": "6918fd3796fa369ccd36c4e4"
}

### Delete a car
DELETE http://localhost:8080/cars/6918fffefc6602bc1c614979
