// ======================================
// PRODUCTION
// ======================================

### Register (create user)
POST https://cse-341-project2-6513.onrender.com/auth/register
Content-Type: application/json

{
  "email": "tester@example.com",
  "password": "test1234",
  "displayName": "Tester"
}

### Login (get token)
POST https://cse-341-project2-6513.onrender.com/auth/login
Content-Type: application/json

{
  "email": "tester@example.com",
  "password": "test1234"
}

### Get all manufacturers (public)
GET https://cse-341-project2-6513.onrender.com/manufacturers

### Create manufacturer (protected) — add Authorization header: Bearer <token>
POST https://cse-341-project2-6513.onrender.com/manufacturers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Honda",
  "country": "Japan",
  "foundedYear": 1948,
  "ceo": "Toshihiro Mibe",
  "totalEmployees": 200000,
  "headquarters": "Tokyo",
  "website": "https://global.honda"
}

### Get all cars (public)
GET https://cse-341-project2-6513.onrender.com/cars

### Create car (protected)
POST https://cse-341-project2-6513.onrender.com/cars
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "model": "Civic",
  "year": 2023,
  "price": 23000,
  "type": "Sedan",
  "manufacturer": "6918fd3796fa369ccd36c4e4",
  "fuel": "Petrol",
  "horsepower": 158
}


// ======================================
// LOCALHOST
// ======================================

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "local@test.com",
  "password": "localpass",
  "displayName": "LocalTester"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "local@test.com",
  "password": "localpass"
}

### Get manufacturers
GET http://localhost:8080/manufacturers

### Create manufacturer (protected)
POST http://localhost:8080/manufacturers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nissan",
  "country": "Japan"
}

### Get cars
GET http://localhost:8080/cars

### Create car (protected)
POST http://localhost:8080/cars
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "model": "Altima",
  "year": 2022,
  "price": 24000,
  "type": "Sedan",
  "manufacturer": "6918fd3796fa369ccd36c4e4",
  "fuel": "Petrol",
  "horsepower": 188
}
